baseurl = "http://hakkard.devosmium.xyz"
languageCode = "en-us"
title = "Hakkard"
theme = "base16"
# Comment the themesDir option if you use this theme in production
#themesDir = "../.."
# google analytics
GoogleAnalytics = "UA-XXXXXX"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "Official News and Resource for the Hakkard RPG World"
  author = "Dev-Osmium"
  keywords = ["hakkard"]
  avatar = "/images/hugo.png"
  displayauthor = true
  # pygments
  PygmentsUseClasses = true
  PygmentsCodeFences = true
  # pagination
  paginate = 10
  paginatePath = "page"
  locale = "en-US"